/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Cadu Santos
 */
public class PesquisaJogos extends javax.swing.JFrame {

    /**
     * Creates new form PesquisaJogos
     */
    public PesquisaJogos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 204));
        setMinimumSize(new java.awt.Dimension(1244, 696));
        getContentPane().setLayout(null);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(40, 60, 830, 30);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        jLabel1.setText("Pesquise aqui um jogo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 10, 160, 30);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"God of war", "Jogo eletrônico de luta, RPG eletrônico, Jogo eletrônico de ação e aventura", "180 mangos  "},
                {"Spider man", "Ação e aventura, super hérois", "120 mangos "},
                {"The Legend of Zelda: Ocarina of Time ", "RPG de aventura", "80 mangos "},
                {"Super Mario World", "Plataforma, aventura", "Grátis"},
                {"Grand Theft Auto V", "Ação e aventura", "180 (100 vip) mangos"},
                {"Minecraft", "Sandbox e Sobrevivência", "80 mangos"},
                {"League of Legends", "MOBA", "Grátis"},
                {"The Legend of Zelda: Breath of the Wild", "RPG, Ação e aventura", "175 mangos "},
                {"Dark Souls Collection", "RPG de ação", "200 mangos(180 vip)"},
                {"The Witcher 3", " RPG de ação", "175 mangos"},
                {"Street Fighter 2 (1991)", "Luta, arcacde", "Grátis "},
                {"World of Warcraft", "MMORPG", "50 mangos (Grátis vip)"},
                {"The Last of Us 1 e 2", "Aventura, Sobrevivência e Horror", "220 mangos"},
                {"Red Dead Redemption 1 e 2", "Ação e aventura , faroeste", "200 mangos"},
                {"Grand Theft Auto: San Andreas ", "Ação e aventura", "Grátis "},
                {"Counter-Strike", "FPS", "Grátis"},
                {"Assassin's Creed legendary collection ", "Aventura e ação", "550 mangos (450 vip)"},
                {"Uncharted Ultimate Collection", "Ação e aventura, shooter", "200 mangos"},
                {"Overwatch", "FPS, hero shooter", "60 mangos"},
                {"The elder scrolls ultimate collection ", "RPG de ação", "150 mangos"}
            },
            new String [] {
                "Título do Jogo", "Gênero", "Preço"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 120, 830, 402);
        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(840, -10, 2, 2);

        jScrollPane3.setBackground(new java.awt.Color(153, 0, 255));
        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(880, 70, 20, 420);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/magnifier.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 20, 34, 14);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/lupa (1).png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 60, 30, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisaJogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisaJogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisaJogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisaJogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisaJogos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
